### ISSUE TITLE
Homebridge crashing with commander exception

### ISSUE THREAD

**Issue by hepcat72** [RockyGJ/homebridge-commander#7]
I started having issues with homebridge yesterday. My RPi was intermittently slowing down and I discovered homebridge had crashed. This morning, I can’t start it up. When i try to start it manually, I see a fatal exception that looks like it’s coming from commander:

```
internal/child_process.js:372
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:372:11)
    at spawn (child_process.js:559:9)
    at Object.execFile (child_process.js:224:15)
    at exec (child_process.js:152:18)
    at commanderCommand.exports.getOutletInUse (/usr/lib/node_modules/homebridge-commander/lib/characteristics.js:267:5)
    at Characteristic.OutletInUse.emit (events.js:197:13)
    at Characteristic.OutletInUse.Characteristic.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Function.module.exports.updateStatus (/usr/lib/node_modules/homebridge-commander/lib/services.js:244:68)
    at commanderCommand.updateStatus (/usr/lib/node_modules/homebridge-commander/index.js:101:12)
    at listOnTimeout (timers.js:327:15)
```

Any idea what’s going on here?

**Comment by hepcat72** [comment]
It appears that the problem was a ton of hung cec-client processes.  I had been using homebridge-hdmi-cec, but it's very buggy with my TV, so I had setup calls to `cec-client -s` with some stuff to save the state of the "switches" for it using homebridge-commander to see if I could make TV commands more reliable.  I don't know what was causing the processes to accumulate, but killing them and removing the commands from the config seems to have solved the problem.
